# Browsertest van alle vijf schermen tegen test/mock_backend.py (Playwright, Chromium uit /opt/pw-browsers).
import os, sys, json
from playwright.sync_api import sync_playwright
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'shots'); os.makedirs(OUT, exist_ok=True)  # draai eerst: python3 test/mock_backend.py
meldingen = []
exe = '/opt/pw-browsers/chromium' if os.path.isfile('/opt/pw-browsers/chromium') else '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
with sync_playwright() as p:
    b = p.chromium.launch(executable_path=exe, headless=True)
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    page = ctx.new_page()
    page.on('console', lambda m: meldingen.append((m.type, m.text)) if m.type in ('error', 'warning') else None)
    page.on('pageerror', lambda e: meldingen.append(('pageerror', str(e))))
    page.goto('http://127.0.0.1:8765/'); page.wait_for_timeout(800)
    page.screenshot(path=OUT + '/00_koppel.png')
    page.fill('#apiInput', 'http://127.0.0.1:8765/api'); page.fill('#codeInput', 'test123'); page.click('#codeOpslaan')
    page.wait_for_selector('#kpis .tegel'); page.wait_for_timeout(500)
    page.screenshot(path=OUT + '/01_vandaag.png', full_page=True)
    page.click('[data-klaar="a1"]'); page.wait_for_timeout(300)
    page.fill('#actieInput', 'Testactie uit de browser'); page.press('#actieInput', 'Enter'); page.wait_for_timeout(600)
    page.screenshot(path=OUT + '/02_vandaag_na.png', full_page=True)
    page.click('nav button[data-view="brein"]'); page.wait_for_selector('#breinTegels .tegel'); page.wait_for_timeout(300)
    page.fill('#vraagInput', 'Wat is het uurtarief voor huiswerkbegeleiding?'); page.click('#vraagKnop'); page.wait_for_selector('.bron'); page.wait_for_timeout(200)
    page.click('[data-typefilter="contract"]'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/03_brein.png', full_page=True)
    page.click('#indexeerKnop'); page.wait_for_timeout(700)
    page.click('nav button[data-view="review"]'); page.wait_for_selector('.quote'); page.wait_for_timeout(200)
    page.click('#reviewEerdere [data-recent]'); page.wait_for_timeout(100)
    page.screenshot(path=OUT + '/04_review.png', full_page=True)
    page.click('#reviewNu'); page.wait_for_timeout(700)
    page.click('nav button[data-view="huisstijl"]'); page.wait_for_selector('.swatch'); page.wait_for_timeout(200)
    page.fill('#contentOnderwerp', 'Start huiswerkbegeleiding op Lyceum Demo'); page.click('#maakContent'); page.wait_for_selector('#contentTekst'); page.wait_for_timeout(400)
    page.screenshot(path=OUT + '/05_huisstijl.png', full_page=True)
    page.click('#huisBewerk'); page.fill('#hToon', 'Nieuwe toonregel\nTweede regel'); page.click('#huisOpslaan'); page.wait_for_timeout(700)
    page.screenshot(path=OUT + '/05b_huisstijl_na_bewerken.png', full_page=True)
    page.click('nav button[data-view="trajecten"]'); page.wait_for_selector('[data-traject]'); page.wait_for_timeout(200)
    page.click('[data-traject="t1"]'); page.wait_for_selector('#tdet-t1 .k-rij'); page.wait_for_timeout(200)
    page.fill('[data-notitieinput="t1"]', 'Notitie uit de test'); page.click('[data-notitie="t1"]'); page.wait_for_timeout(500)
    page.select_option('[data-statuswijzig="t1"]', 'afgerond'); page.wait_for_timeout(500)
    page.screenshot(path=OUT + '/06_trajecten_detail.png', full_page=True)
    page.fill('#trajectZoek', 'demo'); page.wait_for_timeout(200); page.select_option('#fStatus', 'actief'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/07_trajecten_filter.png', full_page=True)
    page.fill('#trajectZoek', ''); page.select_option('#fStatus', ''); page.wait_for_timeout(100)
    page.click('#nieuwTraject'); page.fill('#nSchool', 'Testschool'); page.fill('#nTraject', 'Surveillance'); page.click('#trajectOpslaan'); page.wait_for_timeout(700)
    page.screenshot(path=OUT + '/08_trajecten_nieuw.png', full_page=True)
    page.click('#instellingenKnop'); page.wait_for_selector('#statusInfo .k-rij'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/09_instellingen.png', full_page=True)
    page.click('#koppelSluit')
    page.set_viewport_size({'width': 1100, 'height': 800}); page.click('nav button[data-view="vandaag"]'); page.wait_for_selector('#kpis .tegel'); page.wait_for_timeout(400)
    page.screenshot(path=OUT + '/10_desktop.png', full_page=True)
    print('sw-registraties:', page.evaluate("() => navigator.serviceWorker.getRegistrations().then(r => r.length)"))
    print('--paars:', page.evaluate("() => getComputedStyle(document.documentElement).getPropertyValue('--paars')"))
    print('localStorage:', page.evaluate("() => Object.keys(localStorage)"))
    print('horizontale scroll:', page.evaluate("() => document.documentElement.scrollWidth > document.documentElement.clientWidth"))
    b.close()
print('meldingen:', json.dumps(meldingen, indent=1, ensure_ascii=False) if meldingen else 'geen')
