# Browsertest van alle zes schermen tegen test/mock_backend.py (Playwright, Chromium uit /opt/pw-browsers).
import os, sys, json
from playwright.sync_api import sync_playwright
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'shots'); os.makedirs(OUT, exist_ok=True)  # draai eerst: python3 test/mock_backend.py
meldingen = []
exe = '/opt/pw-browsers/chromium' if os.path.isfile('/opt/pw-browsers/chromium') else '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
with sync_playwright() as p:
    b = p.chromium.launch(executable_path=exe, headless=True)
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    page = ctx.new_page()
    page.on('console', lambda m: meldingen.append((m.type, m.text)) if m.type in ('error', 'warning') else None)
    page.on('pageerror', lambda e: meldingen.append(('pageerror', str(e))))
    page.on('response', lambda r: meldingen.append(('http', str(r.status) + ' ' + r.url)) if r.status >= 400 else None)
    page.goto('http://127.0.0.1:8765/'); page.wait_for_timeout(800)
    page.screenshot(path=OUT + '/00_koppel.png')
    page.fill('#apiInput', 'http://127.0.0.1:8765/api'); page.fill('#codeInput', 'test123'); page.click('#codeOpslaan')
    page.wait_for_selector('#kpis .tegel'); page.wait_for_timeout(500)
    page.screenshot(path=OUT + '/01_vandaag.png', full_page=True)
    page.click('[data-klaar="a1"]'); page.wait_for_timeout(300)
    page.fill('#actieInput', 'Testactie uit de browser'); page.press('#actieInput', 'Enter'); page.wait_for_timeout(600)
    page.screenshot(path=OUT + '/02_vandaag_na.png', full_page=True)
    page.click('nav button[data-view="brein"]'); page.wait_for_selector('#breinTegels .tegel'); page.wait_for_timeout(300)
    page.fill('#vraagInput', 'Wat is het uurtarief voor huiswerkbegeleiding?'); page.click('#vraagKnop'); page.wait_for_selector('.bron'); page.wait_for_timeout(200)
    # v3.5: assistent met actiekaarten — offerte aanpassen en uitvoeren, taak annuleren
    page.fill('#vraagInput', 'Schrijf offerte onderwijsondersteuning voor Voorbeeldcollege, 2 ondersteuners per dag van 10-16u'); page.click('#vraagKnop')
    page.wait_for_selector('.actiekaart'); assert page.locator('.actiekaart').count() == 2
    kaart = page.locator('.actiekaart').first
    kaart.locator('[data-ak="aanpassen"]').click(); page.locator('.actiekaart').first.locator('[data-akveld="titel"]').fill('Onderwijsondersteuning leerplein')
    page.screenshot(path=OUT + '/03b_brein_aanpassen.png', full_page=True)
    page.locator('.actiekaart').first.locator('[data-ak="uitvoeren"]').click(); page.wait_for_selector('.actiekaart.uitgevoerd')
    assert 'Openen' in page.locator('.actiekaart.uitgevoerd').inner_text()
    page.locator('.actiekaart').nth(1).locator('[data-ak="annuleren"]').click(); page.wait_for_selector('.actiekaart.geannuleerd')
    uit = page.evaluate("JSON.parse(localStorage.getItem('aa_chat')).slice(-1)[0].acties.map(function(a){return a.status + ':' + (a.invoer.titel||'')})")
    assert uit == ['uitgevoerd:Onderwijsondersteuning leerplein', 'geannuleerd:'], uit
    page.screenshot(path=OUT + '/03c_brein_acties.png', full_page=True)
    page.click('[data-typefilter="contract"]'); page.wait_for_timeout(200)
    page.click('[data-typefilter=""]'); page.locator('#docLijst [data-docbewerk]').first.click(); page.wait_for_selector('#venster.aan #cf-type')  # v3.7
    page.select_option('#venster #cf-type', 'voorstel'); page.click('#venster [data-cf-opslaan]'); page.wait_for_selector('#venster.aan', state='detached'); page.wait_for_selector('#toast.aan:has-text("Document bijgewerkt")')
    page.click('[data-typefilter="contract"]'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/03_brein.png', full_page=True)
    page.click('#indexeerKnop'); page.wait_for_timeout(700)
    page.click('nav button[data-view="review"]'); page.wait_for_selector('.quote'); page.wait_for_timeout(200)
    page.click('#reviewEerdere [data-recent]'); page.wait_for_timeout(100)
    page.screenshot(path=OUT + '/04_review.png', full_page=True)
    page.click('#reviewNu'); page.wait_for_timeout(700)
    page.click('nav button[data-view="huisstijl"]'); page.wait_for_selector('.swatch'); page.wait_for_timeout(200)
    page.fill('#contentOnderwerp', 'Start huiswerkbegeleiding op Lyceum Demo'); page.click('#maakContent'); page.wait_for_selector('#contentTekst'); page.wait_for_timeout(400)
    page.screenshot(path=OUT + '/05_huisstijl.png', full_page=True)
    page.locator('#recentContent .recent').first.click(); page.locator('#recentContent [data-contentbewerk]').first.click(); page.wait_for_selector('#venster.aan #cf-tekst')  # v3.7
    page.fill('#cf-tekst', 'Aangepaste tekst uit de test'); page.click('#venster [data-cf-opslaan]'); page.wait_for_selector('#recentContent:has-text("Aangepaste tekst uit de test")')
    page.click('#huisBewerk'); page.fill('#hToon', 'Nieuwe toonregel\nTweede regel'); page.fill('#hBedrijf', 'AthenaSchool BV'); page.click('#huisOpslaan'); page.wait_for_selector('#toast.aan:has-text("Huisstijl opgeslagen")')
    page.screenshot(path=OUT + '/05b_huisstijl_na_bewerken.png', full_page=True)
    page.click('nav button[data-view="trajecten"]'); page.wait_for_selector('[data-traject]'); page.wait_for_timeout(200)
    page.click('[data-traject="t1"]'); page.wait_for_selector('#tdet-t1 .k-rij'); page.wait_for_timeout(200)
    page.fill('[data-notitieinput="t1"]', 'Notitie uit de test'); page.click('[data-notitie="t1"]'); page.wait_for_timeout(500)
    page.select_option('[data-statuswijzig="t1"]', 'afgerond'); page.wait_for_timeout(500)
    page.click('[data-trajectbewerk="t1"]'); page.wait_for_selector('#venster.aan #cf-urenPerWeek'); page.fill('#venster #cf-urenPerWeek', '12'); page.click('#venster [data-cf-opslaan]')  # v3.7
    page.wait_for_selector('#tdet-t1:has-text("12 u/wk")')
    page.locator('#tdet-t1 [data-notitiebewerk]').first.click(); page.wait_for_selector('#venster.aan #cf-tekst'); page.fill('#venster #cf-tekst', 'Notitie aangepast'); page.click('#venster [data-cf-opslaan]'); page.wait_for_selector('#tdet-t1:has-text("Notitie aangepast")')
    page.screenshot(path=OUT + '/06_trajecten_detail.png', full_page=True)
    page.fill('#trajectZoek', 'demo'); page.wait_for_timeout(200); page.select_option('#fStatus', 'actief'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/07_trajecten_filter.png', full_page=True)
    page.fill('#trajectZoek', ''); page.select_option('#fStatus', ''); page.wait_for_timeout(100)
    page.click('#nieuwTraject'); page.fill('#nSchool', 'Testschool'); page.fill('#nTraject', 'Surveillance'); page.click('#trajectOpslaan'); page.wait_for_timeout(700)
    page.screenshot(path=OUT + '/08_trajecten_nieuw.png', full_page=True)
    # v2.0: Relaties (CRM)
    page.on('dialog', lambda dl: dl.accept('Te duur') if dl.type == 'prompt' else dl.accept())
    page.click('nav button[data-view="relaties"]'); page.wait_for_selector('#crmInhoud [data-crm-open="school:s1"]'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/11_relaties_scholen.png', full_page=True)
    page.fill('#crmZoek', 'lyceum'); page.wait_for_timeout(150); assert page.locator('#crmInhoud [data-crm-open^="school:"]').count() == 1, 'zoeken op school'
    page.fill('#crmZoek', ''); page.wait_for_timeout(100)
    page.click('[data-crm-open="school:s1"]'); page.wait_for_selector('.detailkop h2'); page.wait_for_timeout(200)
    page.click('[data-composer="gesprek"]'); page.fill('#cf-onderwerp', 'Evaluatie periode 1'); page.fill('#cf-tekst', 'Tevreden over de ondersteuner.'); page.click('[data-cf-opslaan]')
    page.wait_for_selector('.t-item:has-text("Evaluatie periode 1")'); page.wait_for_timeout(200)
    page.locator('.t-item:has-text("Evaluatie periode 1") [data-actbewerk]').click(); page.wait_for_selector('#venster.aan #cf-onderwerp')  # v3.7
    page.fill('#cf-onderwerp', 'Evaluatie periode 1 (bijgesteld)'); page.click('#venster [data-cf-opslaan]'); page.wait_for_selector('.t-item:has-text("(bijgesteld)")')
    page.screenshot(path=OUT + '/12b_tijdlijn_bewerken.png', full_page=True)
    page.screenshot(path=OUT + '/12_school_detail.png', full_page=True)
    page.click('[data-composer="afspraak"]'); page.click('[data-cf-opslaan]'); page.wait_for_selector('.t-item:has-text("Gesprek Voorbeeldcollege Zuid")'); page.wait_for_timeout(100)
    page.locator('.t-item:has-text("Gesprek Voorbeeldcollege Zuid") [data-actbewerk]').first.click(); page.wait_for_selector('#venster.aan [data-actweg]'); page.click('#venster [data-actweg]')  # v3.7: verwijderen
    page.wait_for_selector('.t-item:has-text("Gesprek Voorbeeldcollege Zuid")', state='detached')
    page.click('[data-composer="persoon"]'); page.fill('#cf-voornaam', 'Dirk'); page.fill('#cf-achternaam', 'Smit'); page.click('[data-cf-opslaan]'); page.wait_for_selector('.rij:has-text("Dirk Smit")')
    # v3.3: bewerken stuurt alleen gewijzigde velden; een gelijktijdige wijziging van hetzelfde veld geeft een melding
    page.click('[data-composer="bewerk"]'); page.fill('#cf-plaats', 'Schiedam')
    page.evaluate("() => run('apiSchoolOpslaan', { id: 's1', plaats: 'Vlaardingen', _oud: { plaats: 'Rotterdam' } })")  # een collega was net eerder
    page.wait_for_timeout(300); page.click('[data-cf-opslaan]'); page.wait_for_selector('#toast.aan:has-text("Intussen gewijzigd")'); page.wait_for_timeout(600)
    assert 'Vlaardingen' in page.inner_text('.detailkop p'), 'scherm ververst met de wijziging van de collega'
    page.click('[data-composer="bewerk"]'); page.fill('#cf-bestuur', 'Stichting Nieuw'); page.click('[data-cf-opslaan]'); page.wait_for_selector('.detailkop p:has-text("Stichting Nieuw")')
    page.click('[data-archief]'); page.wait_for_selector('#archiefTijdlijn .t-item')
    page.go_back(); page.wait_for_selector('#crmLijstScherm [data-crmtab]'); page.wait_for_timeout(150)
    page.click('[data-crmtab="pipeline"]'); page.wait_for_selector('.kolom'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/13_pipeline.png', full_page=True)
    page.click('.kaartje[data-crm-open="kans:k1"]'); page.wait_for_selector('[data-kansfase]'); page.wait_for_timeout(150)
    page.select_option('[data-kansfase]', 'onderhandeling'); page.wait_for_selector('.t-item:has-text("voorstel → onderhandeling")'); page.wait_for_timeout(150)
    page.click('[data-composer="track"]'); page.click('[data-cf-opslaan]'); page.wait_for_timeout(500)
    page.screenshot(path=OUT + '/14_kans_detail.png', full_page=True)
    page.click('[data-crm-terug]'); page.wait_for_selector('.kolom'); page.wait_for_timeout(100)
    page.click('[data-crmtab="taken"]'); page.wait_for_selector('[data-taakklaar]'); page.wait_for_timeout(150)
    page.click('[data-taakklaar="tk1"]'); page.wait_for_timeout(500)
    page.click('[data-crmnieuw="taak"]'); page.fill('#cf-tekst', 'Offerte surveillance maken'); page.click('[data-cf-opslaan]'); page.wait_for_selector('.rij:has-text("Offerte surveillance maken")'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/15_taken.png', full_page=True)
    page.click('.rij [data-taakbewerk]:has-text("Offerte surveillance maken")'); page.wait_for_selector('#venster.aan #cf-tekst')  # v3.7
    page.screenshot(path=OUT + '/15b_taak_venster.png', full_page=True)
    page.fill('#venster #cf-tekst', 'Offerte surveillance versturen'); page.select_option('#venster #cf-prio', 'hoog'); page.click('#venster [data-cf-opslaan]')
    page.wait_for_selector('.rij:has-text("Offerte surveillance versturen")', timeout=1500)  # meteen zichtbaar, zonder te herladen
    page.click('[data-taakbewerk="tk1"]'); page.wait_for_selector('#venster.aan [data-taakheropen]'); page.click('[data-taakheropen]'); page.wait_for_selector('[data-taakklaar="tk1"]')
    page.click('[data-taakbewerk="tk2"]'); page.wait_for_selector('#venster.aan [data-taakweg]'); page.click('[data-taakweg]'); page.wait_for_selector('[data-taakbewerk="tk2"]', state='detached')
    page.click('[data-crmtab="rapport"]'); page.wait_for_selector('.tabel'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/16_rapport.png', full_page=True)
    print('horizontale scroll (rapport):', page.evaluate("() => document.documentElement.scrollWidth > document.documentElement.clientWidth"))
    page.wait_for_selector('#rapportActiviteit .t-item')  # v3.3: activiteit per gebruiker
    page.click('[data-beheer="gebruikers"]'); page.wait_for_selector('#cf-naam'); page.fill('#cf-naam', 'Sanne'); page.fill('#cf-email', 'sanne@voorbeeld.nl'); page.select_option('#cf-rol', 'adviseur'); page.click('[data-cf-opslaan]'); page.wait_for_selector('.codevak'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/17_beheer_gebruikers.png', full_page=True)
    page.click('[data-gbewerk="g1"]'); page.wait_for_selector('#venster.aan #cf-naam'); page.fill('#venster #cf-naam', 'Mees de Jong'); page.click('#venster [data-cf-opslaan]'); page.wait_for_selector('#crmBeheer:has-text("Mees de Jong")')  # v3.7
    page.click('[data-beheer="keuzelijsten"]'); page.wait_for_selector('#le-schoolStatussen .le-rij'); page.locator('#le-schoolStatussen .le-rij input').first.fill('nieuw'); page.click('#crmBeheer [data-cf-opslaan]'); page.wait_for_selector('#toast.aan:has-text("Keuzelijsten opgeslagen")')
    page.click('[data-beheer="mijlpalen"]'); page.wait_for_selector('#leMijlpalen .le-rij'); page.click('[data-le-erbij="leMijlpalen"]'); inp = page.locator('#leMijlpalen .le-rij').last.locator('input')
    inp.nth(0).fill('Scholen'); inp.nth(1).fill('contract'); inp.nth(2).fill('90'); inp.nth(3).fill('5'); page.screenshot(path=OUT + '/17b_beheer_mijlpalen.png', full_page=True); page.click('#crmBeheer [data-cf-opslaan]'); page.wait_for_selector('#toast.aan:has-text("Mijlpalen opgeslagen")')
    page.click('[data-beheer="tags"]'); page.wait_for_selector('#crmBeheer [data-hernoem]')
    page.click('[data-beheer="doelen"]'); page.wait_for_selector('#venster.aan [data-doelbewerk]'); page.locator('[data-doelbewerk]').first.click(); page.wait_for_selector('#venster.aan #cf-doel'); page.fill('#venster #cf-doel', '12'); page.click('#venster [data-cf-opslaan]'); page.wait_for_selector('#venster.aan [data-doelbewerk]'); page.click('#venster [data-cf-annuleer]')
    page.click('[data-beheer="capsule"]'); page.wait_for_selector('#crmBeheer:has-text("klaar")', timeout=8000)
    page.click('[data-crmtab="scholen"]'); page.click('[data-crmnieuw="school"]'); page.fill('#cf-naam', 'Testschool Noord'); page.fill('#cf-plaats', 'Groningen'); page.click('[data-cf-opslaan]'); page.wait_for_selector('.detailkop h2:has-text("Testschool Noord")')
    page.click('[data-composer="kans"]'); page.fill('#cf-naam', 'Studentdocenten'); page.fill('#cf-waarde', '8000'); page.click('[data-cf-opslaan]'); page.wait_for_selector('[data-kansfase]')
    page.select_option('[data-kansfase]', 'gewonnen'); page.wait_for_selector('.t-item:has-text("→ gewonnen")'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/18_kans_gewonnen.png', full_page=True)
    page.click('nav button[data-view="vandaag"]'); page.wait_for_selector('#kansenLijst [data-crm-open]'); page.click('#kansenLijst [data-crm-open="kans:k2"]'); page.wait_for_selector('[data-kansfase]'); page.wait_for_timeout(150)
    assert page.locator('#view-relaties.actief').count() == 1, 'kans vanuit Vandaag opent in Relaties'
    page.click('#instellingenKnop'); page.wait_for_selector('#statusInfo .k-rij'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/09_instellingen.png', full_page=True)
    page.click('#koppelSluit')
    # v3.0: desktopweergave (zijbalk, Capsule-opbouw)
    page.set_viewport_size({'width': 1280, 'height': 800}); page.wait_for_timeout(300)
    assert page.locator('body.desk #zijbalk').is_visible(), 'zijbalk op desktop'
    page.click('.zb-item[data-desk="home"]'); page.wait_for_selector('#homeInhoud .hkaart'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/20_desk_home.png')
    page.click('.zb-item[data-desk="contacten"]'); page.wait_for_selector('.dtabel tr.klik'); page.wait_for_timeout(150)
    page.click('th[data-sorteer="plaats"]'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/21_desk_contacten.png')
    page.click('#crmBalk [data-crmtab="personen"]'); page.wait_for_selector('.dtabel tr[data-crm-open^="persoon:"]')
    page.click('#crmBalk [data-crmtab="scholen"]'); page.click('.dtabel tr[data-crm-open="school:s1"]'); page.wait_for_selector('.detail-grid'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/22_desk_school.png')
    page.click('.zb-item[data-desk="taken"]'); page.wait_for_selector('.dtabel [data-taakklaar]'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/23_desk_taken.png')
    page.locator('.dtabel tr[data-taakbewerk] td:nth-child(2)').first.click(); page.wait_for_selector('#venster.aan #cf-tekst'); page.screenshot(path=OUT + '/23b_desk_taak_venster.png'); page.click('#venster [data-cf-annuleer]')  # v3.7
    page.click('.zb-item[data-desk="agenda"]'); page.wait_for_selector('.maand .dag'); page.wait_for_timeout(200)
    page.screenshot(path=OUT + '/24_desk_agenda.png')
    page.click('[data-agnav="1"]'); page.wait_for_timeout(300); page.click('[data-agnav="0"]'); page.wait_for_selector('.maand .dag.vandaag')
    page.click('[data-agendaplan]'); page.wait_for_selector('#agendaForm #cf-schoolId'); page.select_option('#cf-schoolId', 's1'); page.fill('#cf-titel', 'Evaluatie'); page.click('#agendaForm [data-cf-opslaan]'); page.wait_for_timeout(500)
    page.click('.zb-item[data-desk="pipeline"]'); page.wait_for_selector('.kolom'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/25_desk_pipeline.png')
    page.click('.zb-item[data-desk="projecten"]'); page.wait_for_selector('[data-projectopen]'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/26_desk_projecten.png')
    page.click('[data-projectopen="t1"]'); page.wait_for_selector('#tdet-t1 .k-rij')
    page.click('.zb-item[data-desk="rapporten"]'); page.wait_for_selector('.tabel'); page.wait_for_timeout(150)
    page.click('.zb-item[data-desk="doelen"]'); page.wait_for_selector('.doel-rij'); page.wait_for_timeout(150)
    page.screenshot(path=OUT + '/27_desk_doelen.png')
    page.fill('#zbZoek', 'lyceum'); page.wait_for_selector('#zbResultaten.aan a'); page.click('#zbResultaten a'); page.wait_for_selector('.detail-grid h2:has-text("Lyceum Demo")')
    page.click('#zbNieuwKnop'); page.click('[data-desknieuw="taak"]'); page.wait_for_selector('#crmNieuw #cf-tekst')
    page.click('.zb-item[data-desk="home"]'); page.wait_for_selector('#homeMails [data-concept]'); page.click('#homeMails [data-concept]')  # v3.5
    page.wait_for_selector('.actiekaart:has-text("Conceptmail")'); assert page.locator('#view-brein').is_visible()
    page.screenshot(path=OUT + '/28_desk_brein_concept.png')
    page.click('.zb-item[data-desk="brein"]'); page.wait_for_selector('#breinTegels .tegel')
    for breedte in (1280, 1024):
        page.set_viewport_size({'width': breedte, 'height': 800}); page.wait_for_timeout(200)
        print('horizontale scroll desktop', breedte, page.evaluate("() => document.documentElement.scrollWidth > document.documentElement.clientWidth"))
    page.click('.zb-item[data-desk="contacten"]'); page.click('.dtabel tr[data-crm-open="school:s1"]'); page.wait_for_selector('.detail-grid')
    page.click('[data-composer="notitie"]'); page.fill('#cf-tekst', 'Half getypt')
    page.set_viewport_size({'width': 900, 'height': 800}); page.wait_for_timeout(200); page.set_viewport_size({'width': 1280, 'height': 800}); page.wait_for_timeout(200)
    assert page.input_value('#cf-tekst') == 'Half getypt', 'concept blijft bij wisselen van breedte'
    page.click('[data-cf-annuleer]')
    page.set_viewport_size({'width': 390, 'height': 844}); page.wait_for_timeout(300)
    assert not page.locator('#zijbalk').is_visible() and page.locator('nav').is_visible(), 'terug naar mobiel'
    page.set_viewport_size({'width': 1100, 'height': 800}); page.wait_for_timeout(300); page.click('.zb-item[data-desk="home"]'); page.wait_for_selector('#homeInhoud .hkaart'); page.wait_for_timeout(300)
    page.screenshot(path=OUT + '/10_desktop.png', full_page=True)
    # v3.2: met een trage backend (2 s) moet Home na herladen meteen gevuld zijn uit de bewaarde gegevens
    def traag(route):
        import time; time.sleep(2); route.continue_()
    page.route('**/api*', traag)
    page.reload(); page.wait_for_selector('#homeInhoud .hkaart', timeout=1500)
    print('home direct uit bewaarde gegevens: ja')
    page.wait_for_selector('#homeMails .rij', timeout=15000); page.unroute('**/api*', traag)
    print('sw-registraties:', page.evaluate("() => navigator.serviceWorker.getRegistrations().then(r => r.length)"))
    print('--paars:', page.evaluate("() => getComputedStyle(document.documentElement).getPropertyValue('--paars')"))
    print('localStorage:', page.evaluate("() => Object.keys(localStorage)"))
    print('horizontale scroll:', page.evaluate("() => document.documentElement.scrollWidth > document.documentElement.clientWidth"))
    b.close()
print('meldingen:', json.dumps(meldingen, indent=1, ensure_ascii=False) if meldingen else 'geen')
